"""Structured output contracts for awin."""

from awin.contracts.m0 import (
    AlertChange,
    AlertDiffResult,
    AlertMaterial,
    AlertOutput,
    CandidateItem,
    MarketEvidenceBundle,
    MarketFundEvidence,
    MarketUnderstandingOutput,
    MetaThemeItem,
    M0SnapshotBundle,
    OpportunityDiscoveryOutput,
    RiskSurveillanceOutput,
    RunContext,
    StockEvidenceBundle,
    StockEvidenceItem,
    StyleRankingItem,
    ThemeEvidenceItem,
)

__all__ = [
    "AlertChange",
    "AlertDiffResult",
    "AlertMaterial",
    "AlertOutput",
    "CandidateItem",
    "MarketEvidenceBundle",
    "MarketFundEvidence",
    "MarketUnderstandingOutput",
    "MetaThemeItem",
    "M0SnapshotBundle",
    "OpportunityDiscoveryOutput",
    "RiskSurveillanceOutput",
    "RunContext",
    "StockEvidenceBundle",
    "StockEvidenceItem",
    "StyleRankingItem",
    "ThemeEvidenceItem",
]
