from __future__ import annotations

CREATE_TABLE_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS monitor_run (
        run_id TEXT PRIMARY KEY,
        trade_date TEXT NOT NULL,
        snapshot_time TEXT NOT NULL,
        analysis_snapshot_ts TEXT NOT NULL,
        round_seq INTEGER,
        source_status TEXT,
        fallback_used INTEGER NOT NULL DEFAULT 0,
        freshness_seconds INTEGER,
        coverage_ratio REAL,
        market_regime TEXT,
        style_state TEXT,
        top_attack_lines TEXT,
        has_update INTEGER NOT NULL DEFAULT 0,
        alert_level TEXT,
        stock_count INTEGER NOT NULL DEFAULT 0,
        confirmed_style TEXT,
        latest_status TEXT,
        latest_dominant_style TEXT,
        top_meta_themes_json TEXT,
        summary_line TEXT,
        alert_decision TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS stock_snapshot (
        run_id TEXT NOT NULL,
        trade_date TEXT NOT NULL,
        snapshot_time TEXT NOT NULL,
        analysis_snapshot_ts TEXT NOT NULL,
        symbol TEXT NOT NULL,
        stock_code TEXT,
        stock_name TEXT,
        exchange TEXT,
        market TEXT,
        industry TEXT,
        last_price REAL,
        last_close REAL,
        open_price REAL,
        high_price REAL,
        low_price REAL,
        volume REAL,
        bid_volume1 REAL,
        ask_volume1 REAL,
        pct_chg_prev_close REAL,
        open_ret REAL,
        range_position REAL,
        amount REAL,
        turnover_rate REAL,
        volume_ratio REAL,
        amplitude REAL,
        float_mkt_cap REAL,
        total_mkt_cap REAL,
        money_pace_ratio REAL,
        main_net_inflow REAL,
        super_net REAL,
        large_net REAL,
        ret_3d REAL,
        ret_5d REAL,
        ret_10d REAL,
        ret_20d REAL,
        dividend_value_score REAL,
        quality_growth_score REAL,
        high_beta_attack_score REAL,
        low_vol_defensive_score REAL,
        dividend_style TEXT,
        valuation_style TEXT,
        growth_style TEXT,
        quality_style TEXT,
        volatility_style TEXT,
        ownership_style TEXT,
        capacity_bucket TEXT,
        composite_style_labels_json TEXT,
        main_net_amount_5d_sum REAL,
        inflow_streak_days INTEGER,
        outflow_streak_days INTEGER,
        flow_acceleration_3d REAL,
        price_flow_divergence_flag INTEGER NOT NULL DEFAULT 0,
        style_bucket TEXT,
        best_meta_theme TEXT,
        best_concept TEXT,
        theme_names_json TEXT,
        style_names_json TEXT,
        signal_state TEXT,
        display_bucket TEXT,
        risk_tag TEXT,
        confidence_score REAL,
        research_coverage_score REAL,
        research_hooks_json TEXT,
        source_status TEXT,
        fallback_used INTEGER NOT NULL DEFAULT 0,
        freshness_seconds INTEGER,
        coverage_ratio REAL,
        is_core_anchor INTEGER NOT NULL DEFAULT 0,
        is_new_long INTEGER NOT NULL DEFAULT 0,
        is_catchup INTEGER NOT NULL DEFAULT 0,
        is_short INTEGER NOT NULL DEFAULT 0,
        is_watchlist INTEGER NOT NULL DEFAULT 0,
        is_warning INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (run_id, symbol),
        FOREIGN KEY (run_id) REFERENCES monitor_run (run_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS alert_log (
        alert_id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL,
        alert_type TEXT NOT NULL,
        severity TEXT,
        entity_type TEXT,
        entity_key TEXT,
        title TEXT,
        message TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (run_id) REFERENCES monitor_run (run_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS style_profile (
        trade_date TEXT NOT NULL,
        symbol TEXT NOT NULL,
        market_type_label TEXT,
        exchange_label TEXT,
        ownership_style TEXT,
        legacy_industry_label TEXT,
        sw_l1_code TEXT,
        sw_l1_name TEXT,
        sw_l2_code TEXT,
        sw_l2_name TEXT,
        sw_l3_code TEXT,
        sw_l3_name TEXT,
        free_float_share REAL,
        float_mv REAL,
        total_mv REAL,
        avg_amount_20d REAL,
        size_bucket_pct TEXT,
        size_bucket_abs TEXT,
        capacity_bucket TEXT,
        dividend_value_score REAL,
        growth_valuation_score REAL,
        quality_growth_score REAL,
        sales_growth_score REAL,
        profit_growth_score REAL,
        low_vol_defensive_score REAL,
        high_beta_attack_score REAL,
        dividend_style TEXT,
        valuation_style TEXT,
        growth_style TEXT,
        quality_style TEXT,
        volatility_style TEXT,
        composite_style_labels_json TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (trade_date, symbol)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS run_artifact (
        artifact_id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL,
        artifact_name TEXT NOT NULL,
        artifact_format TEXT NOT NULL,
        content_level TEXT,
        relative_path TEXT,
        table_name TEXT,
        row_count INTEGER,
        byte_size INTEGER,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (run_id) REFERENCES monitor_run (run_id)
    )
    """,
]

MIGRATION_ADD_COLUMNS = {
    "monitor_run": [
        "trade_date TEXT",
        "snapshot_time TEXT",
        "analysis_snapshot_ts TEXT",
        "round_seq INTEGER",
        "source_status TEXT",
        "fallback_used INTEGER DEFAULT 0",
        "freshness_seconds INTEGER",
        "coverage_ratio REAL",
        "market_regime TEXT",
        "style_state TEXT",
        "top_attack_lines TEXT",
        "has_update INTEGER DEFAULT 0",
        "alert_level TEXT",
        "stock_count INTEGER DEFAULT 0",
        "confirmed_style TEXT",
        "latest_status TEXT",
        "latest_dominant_style TEXT",
        "top_meta_themes_json TEXT",
        "summary_line TEXT",
        "alert_decision TEXT",
        "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
    ],
    "stock_snapshot": [
        "trade_date TEXT",
        "snapshot_time TEXT",
        "analysis_snapshot_ts TEXT",
        "stock_code TEXT",
        "stock_name TEXT",
        "exchange TEXT",
        "market TEXT",
        "industry TEXT",
        "last_price REAL",
        "last_close REAL",
        "open_price REAL",
        "high_price REAL",
        "low_price REAL",
        "volume REAL",
        "bid_volume1 REAL",
        "ask_volume1 REAL",
        "pct_chg_prev_close REAL",
        "open_ret REAL",
        "range_position REAL",
        "amount REAL",
        "turnover_rate REAL",
        "volume_ratio REAL",
        "amplitude REAL",
        "float_mkt_cap REAL",
        "total_mkt_cap REAL",
        "money_pace_ratio REAL",
        "main_net_inflow REAL",
        "super_net REAL",
        "large_net REAL",
        "ret_3d REAL",
        "ret_5d REAL",
        "ret_10d REAL",
        "ret_20d REAL",
        "dividend_value_score REAL",
        "quality_growth_score REAL",
        "high_beta_attack_score REAL",
        "low_vol_defensive_score REAL",
        "dividend_style TEXT",
        "valuation_style TEXT",
        "growth_style TEXT",
        "quality_style TEXT",
        "volatility_style TEXT",
        "ownership_style TEXT",
        "capacity_bucket TEXT",
        "composite_style_labels_json TEXT",
        "main_net_amount_5d_sum REAL",
        "inflow_streak_days INTEGER",
        "outflow_streak_days INTEGER",
        "flow_acceleration_3d REAL",
        "price_flow_divergence_flag INTEGER DEFAULT 0",
        "style_bucket TEXT",
        "best_meta_theme TEXT",
        "best_concept TEXT",
        "theme_names_json TEXT",
        "style_names_json TEXT",
        "signal_state TEXT",
        "display_bucket TEXT",
        "risk_tag TEXT",
        "confidence_score REAL",
        "research_coverage_score REAL",
        "research_hooks_json TEXT",
        "source_status TEXT",
        "fallback_used INTEGER DEFAULT 0",
        "freshness_seconds INTEGER",
        "coverage_ratio REAL",
        "is_core_anchor INTEGER DEFAULT 0",
        "is_new_long INTEGER DEFAULT 0",
        "is_catchup INTEGER DEFAULT 0",
        "is_short INTEGER DEFAULT 0",
        "is_watchlist INTEGER DEFAULT 0",
        "is_warning INTEGER DEFAULT 0",
        "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
    ],
    "alert_log": [
        "severity TEXT",
        "entity_type TEXT",
        "entity_key TEXT",
        "title TEXT",
        "message TEXT",
        "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
    ],
    "style_profile": [
        "market_type_label TEXT",
        "exchange_label TEXT",
        "ownership_style TEXT",
        "legacy_industry_label TEXT",
        "sw_l1_code TEXT",
        "sw_l1_name TEXT",
        "sw_l2_code TEXT",
        "sw_l2_name TEXT",
        "sw_l3_code TEXT",
        "sw_l3_name TEXT",
        "free_float_share REAL",
        "float_mv REAL",
        "total_mv REAL",
        "avg_amount_20d REAL",
        "size_bucket_pct TEXT",
        "size_bucket_abs TEXT",
        "capacity_bucket TEXT",
        "dividend_value_score REAL",
        "growth_valuation_score REAL",
        "quality_growth_score REAL",
        "sales_growth_score REAL",
        "profit_growth_score REAL",
        "low_vol_defensive_score REAL",
        "high_beta_attack_score REAL",
        "dividend_style TEXT",
        "valuation_style TEXT",
        "growth_style TEXT",
        "quality_style TEXT",
        "volatility_style TEXT",
        "composite_style_labels_json TEXT",
        "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
    ],
    "run_artifact": [
        "artifact_id INTEGER",
        "artifact_name TEXT",
        "artifact_format TEXT",
        "content_level TEXT",
        "relative_path TEXT",
        "table_name TEXT",
        "row_count INTEGER",
        "byte_size INTEGER",
        "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
    ],
}

INDEX_STATEMENTS = [
    """
    CREATE INDEX IF NOT EXISTS idx_monitor_run_trade_date_snapshot
    ON monitor_run (trade_date, snapshot_time)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_stock_snapshot_symbol
    ON stock_snapshot (symbol)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_stock_snapshot_trade_date_snapshot
    ON stock_snapshot (trade_date, snapshot_time)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_stock_snapshot_signal_state
    ON stock_snapshot (signal_state)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_stock_snapshot_best_meta_theme
    ON stock_snapshot (best_meta_theme)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_alert_log_run_id
    ON alert_log (run_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_style_profile_symbol
    ON style_profile (symbol)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_style_profile_trade_date
    ON style_profile (trade_date)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_run_artifact_run_id
    ON run_artifact (run_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_run_artifact_name
    ON run_artifact (artifact_name)
    """,
]
